In [890]:
import numpy as np

In [891]:
import scipy.spatial

In [892]:
data = np.loadtxt("input.txt")

In [893]:
X = data

In [894]:
print(X)

[[ 5.31664467 -1.71114659  0.33101797  0.35269514]
 [ 5.92060757 -2.15461087  0.12105119  0.33576825]
 [ 3.99278021 -1.83245444 -2.43630505  1.6973623 ]
 ...
 [ 1.12439692  2.56058431  3.90159178  2.24084592]
 [ 1.1100539   2.46704149  3.96049976  2.2876184 ]
 [ 1.119699    2.34520769  3.83603096  2.37179136]]


In [895]:
freq = 0.7
for jj in range(1):
    S = scipy.spatial.distance.pdist(X, 'sqeuclidean') / (freq ** 2)
    S = scipy.spatial.distance.squareform(S, force='no', checks=True)
    W = np.exp(-0.5 * S)
    d = W.sum(axis = 0)
    for i in range(len(X)):
        W[i, :] = W[i, :] / d[i]
    X = W.dot(X)

In [896]:
print(X.flatten())

[ 5.56618711 -1.95204165  0.00617596 ...  2.49199029  3.17329386
  2.06938255]
