In [300]:
import numpy as np

In [301]:
import scipy.spatial

In [302]:
data = np.loadtxt("input.txt")

In [303]:
X = data
X

array([[ 5.31664467, -1.71114659,  0.33101797,  0.35269514],
       [ 5.92060757, -2.15461087,  0.12105119,  0.33576825],
       [ 3.99278021, -1.83245444, -2.43630505,  1.6973623 ],
       ...,
       [ 1.12439692,  2.56058431,  3.90159178,  2.24084592],
       [ 1.1100539 ,  2.46704149,  3.96049976,  2.2876184 ],
       [ 1.119699  ,  2.34520769,  3.83603096,  2.37179136]])

In [304]:
freq = 0.7
for jj in range(10):
    S = scipy.spatial.distance.pdist(X, 'sqeuclidean') / (freq ** 2)
    S = scipy.spatial.distance.squareform(S, force='no', checks=True)
    W = np.exp(-0.5 * S)
    d = W.sum(axis = 0)
    for i in range(len(X)):
        W[i, :] = W[i, :] / d[i]
    X = W.dot(X)
X

array([[ 5.16981564, -2.12490052, -2.06759638,  1.98757385],
       [ 5.16981564, -2.12490052, -2.06759638,  1.98757385],
       [ 5.16981564, -2.12490052, -2.06759638,  1.98757385],
       ...,
       [ 1.86964187,  2.46691048,  2.6461041 ,  1.81257716],
       [ 1.86964187,  2.46691048,  2.6461041 ,  1.81257716],
       [ 1.86964187,  2.46691048,  2.6461041 ,  1.81257716]])

In [313]:
S = scipy.spatial.distance.pdist(X, 'sqeuclidean')
S = scipy.spatial.distance.squareform(S, force='no', checks=True)
S

array([[ 0.       ,  0.       ,  0.       , ..., 54.2254712, 54.2254712,
        54.2254712],
       [ 0.       ,  0.       ,  0.       , ..., 54.2254712, 54.2254712,
        54.2254712],
       [ 0.       ,  0.       ,  0.       , ..., 54.2254712, 54.2254712,
        54.2254712],
       ...,
       [54.2254712, 54.2254712, 54.2254712, ...,  0.       ,  0.       ,
         0.       ],
       [54.2254712, 54.2254712, 54.2254712, ...,  0.       ,  0.       ,
         0.       ],
       [54.2254712, 54.2254712, 54.2254712, ...,  0.       ,  0.       ,
         0.       ]])

In [306]:
mask = np.zeros(len(X))

In [307]:
cls = 1

for i in range(len(mask)):
    if mask[i]:
        continue
    mask[i] = cls
    for j in range(i + 1, len(mask)):
        if mask[j]:
            continue
        if S[i][j] < 0.1:
            mask[j] = cls
    cls += 1

In [321]:
mask

array([1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 3., 3., 2., 2., 4., 2., 5., 2., 5., 5., 5.,
       5., 2., 6., 5., 5., 2., 2., 6., 6., 6., 5., 5., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 6., 6., 6., 6., 6., 6., 6., 6., 5., 5.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 2., 2., 2.